# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56c0050084287e9503815baf3843a8e4a98867d6948cd4e18bec322db41b0299d989c71c0e3a8bdb4ffd5b19745b97d315588e2b859cae6cb7c50cc16fa7304d

test:
  secret_key_base: c1657875a3aa4cd7e2e99bba3d660faece069aeea78934cf483e9873a70a845c6bddfa48fd07d65d624326aa98ad5c37196d1310851b02ed5ee84cebe7c41d54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
